"use client"
import {AudioWaveform, Github} from "lucide-react"
import WorkoutWizard from "../components/workout/WorkoutWizard"

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
    {/* Fixed Header */}
    <header className="py-6 bg-white sticky top-0 z-10 border-b">
      <div className="container mx-auto px-4">
        <h1 className="text-3xl font-bold flex items-center gap-2 justify-center">
          <AudioWaveform />
          Smart Cycle Workout
        </h1>
        <p className="text-lg text-center mt-2">A period-aware workout plan generated by AI.</p>
      </div>
    </header>

    {/* Main Content with proper spacing */}
    <main className="flex-1 container mx-auto px-4 py-8">
      <WorkoutWizard />
    </main>

    {/* Fixed Footer */}
    <footer className="py-6 border-t bg-white">
      <div className="container mx-auto px-4 flex justify-center">
        <a
          className="flex items-center gap-2 hover:underline hover:underline-offset-4"
          href="https://github.com/camilarondinini/cycle-smart-workout"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Github />
          Source Code
        </a>
      </div>
    </footer>
  </div>
  )
}


{/* <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 sm:p-10 font-[family-name:var(--font-geist-sans)]">
      <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-center w-full">
        <h1 className="text-3xl font-bold flex items-center gap-2">
          <AudioWaveform />
          Smart Cycle Workout
        </h1>
        <p className="text-lg text-center">A period-aware workout plan generated by AI.</p>
        <WorkoutWizard />
      </main>
      <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
        <a
          className="flex items-center gap-2 hover:underline hover:underline-offset-4"
          href="https://github.com/camilarondinini/cycle-smart-workout"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Github />
          Source Code
        </a>
      </footer>
    </div> */}
