"use client"
import {AudioWaveform, Github} from "lucide-react"
import WorkoutWizard from "../components/workout/WorkoutWizard"

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
    <header className="py-4 bg-white sticky top-0 z-10 border-b">
      <div className="container mx-auto px-4">
        <h1 className="text-2xl font-bold flex items-center gap-2 justify-center">
          <AudioWaveform size={20} />
          Smart Cycle Workout
        </h1>
        <p className="text-base text-center mt-1">A period-aware workout plan generated by AI.</p>
      </div>
    </header>

    <main className="flex-1 container mx-auto px-4 py-6">
      <WorkoutWizard />
    </main>

    <footer className="py-4 border-t bg-white">
      <div className="container mx-auto px-4 flex justify-center">
        <a
          className="flex items-center gap-1.5 hover:underline hover:underline-offset-4 text-sm"
          href="https://github.com/camilarondinini/cycle-smart-workout"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Github size={16} />
          Source Code
        </a>
      </div>
    </footer>
  </div>
  )
}
